//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessKiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessKiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        internal static string detail_command_line {
            get {
                return ResourceManager.GetString("detail_command_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window.
        /// </summary>
        internal static string detail_main_window {
            get {
                return ResourceManager.GetString("detail_main_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        internal static string detail_memory {
            get {
                return ResourceManager.GetString("detail_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string detail_path {
            get {
                return ResourceManager.GetString("detail_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill a process..
        /// </summary>
        internal static string kill_a_process {
            get {
                return ResourceManager.GetString("kill_a_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill a process by IP and port.
        /// </summary>
        internal static string kill_a_process_by_ip_and_port {
            get {
                return ResourceManager.GetString("kill_a_process_by_ip_and_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Killer.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command line of the process in the tool tip.
        /// </summary>
        internal static string setting_show_command_line {
            get {
                return ResourceManager.GetString("setting_show_command_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may slow down the plugin..
        /// </summary>
        internal static string setting_show_command_line_description {
            get {
                return ResourceManager.GetString("setting_show_command_line_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show explorer.exe that hosts Windows Shell.
        /// </summary>
        internal static string setting_show_shell_explorer {
            get {
                return ResourceManager.GetString("setting_show_shell_explorer", resourceCulture);
            }
        }
    }
}
